# Generated by Django 5.1.15 on 2026-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_flightreference_routereference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fuel_category',
        ),
        migrations.AddField(
            model_name='order',
            name='flight_status',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', max_length=20),
        ),
    ]
