# Generated by Django 5.1.15 on 2026-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_fuel_category_order_flight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dr_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
