# Generated by Django 5.1.15 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_dr_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedEmailContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("email",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="approval_email_cc",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="approval_email_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
