# Generated by Django 5.1.15 on 2026-06-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('orders', '0006_order_approval_emails_savedemailcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='aircrafts.aircraft'),
        ),
    ]
