# Generated by Django 5.1.15 on 2026-04-03 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_no', models.CharField(blank=True, max_length=100)),
                ('digital_invoice', models.CharField(blank=True, max_length=100)),
                ('pso_invoice', models.CharField(blank=True, max_length=100)),
                ('pso_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pso_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fueling_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pso_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pso_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bsa_invoice', models.CharField(blank=True, max_length=100)),
                ('bsa_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bsa_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bsa_fueling_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bsa_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bsa_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
