# Generated by Django 5.1.15 on 2026-05-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("financials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financial",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_financials",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="financial",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
