# Generated by Django 5.1.15 on 2026-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_refresh_invoice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='signature_image',
            field=models.FileField(blank=True, upload_to='company/signatures/'),
        ),
    ]
