# Generated by Django 5.1.15 on 2026-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_companyprofile_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='invoice_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
