# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_clientpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpayment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHEQUE", "Cheque"),
                    ("ACCOUNT_TRANSFER", "Account Transfer"),
                    ("CASH", "Cash"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
