# Generated by Django 5.1.15 on 2026-04-24 04:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('aviation_total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('aviation_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('aviation_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pso_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pso_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pso_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-updated_at'),
            },
        ),
    ]
