# Generated by Django 5.1.15 on 2026-05-05 00:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="aviation_dr_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="pso_deposited_manual",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="pso_dr_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="PsoDeposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("cheque_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pso_deposits",
                        to="balance_sheets.balancesheet",
                    ),
                ),
            ],
            options={
                "ordering": ("date", "created_at", "pk"),
            },
        ),
    ]
