# Generated by Codex on 2026-05-09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_clientpayment"),
        ("orders", "0006_order_approval_emails_savedemailcontact"),
        ("balance_sheets", "0002_balancesheet_aviation_dr_no_balancesheet_pso_deposited_manual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheet",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="client_payment",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="balance_sheet_record", to="clients.clientpayment"),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="order",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="balance_sheet", to="orders.order"),
        ),
        migrations.AddConstraint(
            model_name="balancesheet",
            constraint=models.UniqueConstraint(condition=models.Q(order__isnull=True), fields=("date",), name="unique_daily_balance_sheet_date"),
        ),
    ]
