# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0003_balancesheet_client_payment_balancesheet_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="payment_method",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="payment_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
