# Generated by Codex on 2026-05-20

from django.db import migrations, models


def copy_cheque_number_to_reference(apps, schema_editor):
    PsoDeposit = apps.get_model("balance_sheets", "PsoDeposit")
    for deposit in PsoDeposit.objects.exclude(cheque_number="").iterator():
        deposit.reference = deposit.cheque_number
        deposit.save(update_fields=["reference", "updated_at"])


def reverse_copy_reference_to_cheque_number(apps, schema_editor):
    PsoDeposit = apps.get_model("balance_sheets", "PsoDeposit")
    for deposit in PsoDeposit.objects.exclude(reference="").iterator():
        deposit.cheque_number = deposit.reference
        deposit.save(update_fields=["cheque_number", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("balance_sheets", "0004_balancesheet_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="psodeposit",
            name="mode",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="psodeposit",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(copy_cheque_number_to_reference, reverse_copy_reference_to_cheque_number),
        migrations.RemoveField(
            model_name="psodeposit",
            name="cheque_number",
        ),
    ]
